# Database configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgresUser
quarkus.datasource.password=postgresPW
quarkus.datasource.jdbc.url=jdbc:postgresql://127.0.0.1:5432/postgresDB

# Hibernate configuration
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.log.format-sql=true

# REST configuration
quarkus.http.port=8080
quarkus.resteasy-reactive.path=/services

# Reactive Messaging configuration
mp.messaging.incoming.orders.connector=smallrye-in-memory
mp.messaging.outgoing.orders.connector=smallrye-in-memory
